esphome:
  name: doorbell
  on_boot:
    priority: -100
    then:
      - delay: 1s
      - lambda: 'id(wait_on_init) = true;'

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "9f7bf82b4b1d149a2e10bf6812b6f24b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Doorbell Fallback Hotspot"
    password: "Fcgj0H0td68f"

captive_portal:


time:
  - platform: homeassistant
    id: homeassistant_time
 
text_sensor:
  - platform: version
    name: Doorbell ESPHome Version
  - platform: wifi_info
    ip_address:
      name: Doorbell IP
    ssid:
      name: Doorbell SSID
    bssid:
      name: Doorbell BSSID

# wifi sensor
sensor:
  - platform: uptime
    name: Doorbell Uptime
  - platform: wifi_signal
    name: Doorbell WiFi Signal
    update_interval: 60s


globals:
  - id: upstairs_chime
    type: bool
    restore_value: true
    initial_value: 'true'

  - id: groundfloor_chime
    type: bool
    restore_value: true
    initial_value: 'true'
    
  - id: wait_on_init
    type: bool
    restore_value: no
 
switch:

# relay configuration for upstairs doorbell
  - platform: gpio
    pin:
      number: D6
      inverted: false
    name: "Upstairs Doorbell"
    id: upstairs_door_bell
    internal: true
    icon: mdi:alarm-bell

  - platform: gpio
    pin:
      number: D5
      inverted: false
    name: "Groundfloor Doorbell"
    id: groundfloor_door_bell
    internal: true
    icon: mdi:alarm-bell



# enable configuration
  - platform: template
    name: Groundfloor Doorbell Chime Active
    id: groundfloor_chime_active
    restore_state: false
    turn_on_action:
      - globals.set:
          id: groundfloor_chime
          value: 'true'
    turn_off_action:
      - globals.set:
          id: groundfloor_chime
          value: 'false'
    lambda: |-
      return id(groundfloor_chime);

  - platform: template
    name: Upstairs Doorbell Chime Active
    id: upstairs_chime_active
    restore_state: false
    turn_on_action:
      - globals.set:
          id: upstairs_chime
          value: 'true'
    turn_off_action:
      - globals.set:
          id: upstairs_chime
          value: 'false'
    lambda: |-
      return id(upstairs_chime);
      
  - platform: template
    name: Global Doorbell Chime Active
    id: global_chime_active
    restore_state: false
    turn_on_action:
      - globals.set:
          id: upstairs_chime
          value: 'true'
      - globals.set:
          id: groundfloor_chime
          value: 'true'
    turn_off_action:
      - globals.set:
          id: upstairs_chime
          value: 'false'
      - globals.set:
          id: groundfloor_chime
          value: 'false'
    lambda: |-
      return id(upstairs_chime) && id(groundfloor_chime);

  - platform: template
    name: ring door bell
    id: ring
    restore_state: false
    turn_on_action:
      - if: 
          condition:
            - switch.is_on: upstairs_chime_active
          then:
            switch.turn_on: upstairs_door_bell
      - if:
          condition:
            - switch.is_on: groundfloor_chime_active
          then:
            switch.turn_on: groundfloor_door_bell
      - delay: 200ms
      - if: 
          condition:
            - switch.is_on: upstairs_chime_active
          then:
            switch.turn_off: upstairs_door_bell
      - if:
          condition:
            - switch.is_on: groundfloor_chime_active
          then:
            switch.turn_off: groundfloor_door_bell

# system action
  - platform: restart
    name: "Doorbell Restart"

# button configuration
binary_sensor:
  - platform: template
    id: doorbell_sensor
    name: "Doorbell Sensor"
    lambda: |-
      return id(doorbell).state;

  - platform: gpio
    # restore_mode: RESTORE_DEFAULT_OFF
    pin:
      number: D7
      mode: INPUT_PULLUP
      inverted: true
    name: "Doorbell"
    id: doorbell
    filters:
      - delayed_on: 50ms
      - delayed_off: 5000ms # prevents from re-ringing within 5 seconds
    internal: true
    
    on_press:
      then:
        - lambda: |-
            if (id(wait_on_init) == false) {
                return;
            } else {
              id(ring).turn_on();
            }
        - delay: 1s
        - lambda: |-
            if (id(wait_on_init) == false) {
                return;
            } else {
              id(ring).turn_on();
            }
# System status configuration
  - platform: status
    name: "Status Doorbell"
